trigger:
- master
- releases/*

queue: Hosted VS2017

name: $(Major).$(Minor).$(Rev:rr)

steps:
- powershell: |
    Write-Host 'Hello World !'
  displayName: Run a PowerShell Script
  errorActionPreference: stop