trigger:
- master
- releases/*

queue: Hosted VS2017

name: $(Major).$(Minor).$(BuildID)

steps:
- task: PowerShell@1
  inputs:
    scriptType: inlineScript
    inlineScript: ' $PSVersionTable.PSVersion'

- task: qetza.replacetokens.replacetokens-task.replacetokens@2
  inputs:
    rootDirectory: 'PSCodeHealth\task'
    targetFiles: task.json
    writeBOM: false
    actionOnMissing: fail

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'PSCodeHealth\task\task.json'
    ArtifactName: task.json
    publishLocation: Container
