trigger:
- master
- releases/*

queue: Hosted VS2017

name: $(Major).$(Minor).$(BuildID)

steps:
- task: PowerShell@1
  inputs:
    scriptType: inlineScript
    inlineScript: |
     Install-PackageProvider -Name NuGet -Force -Scope CurrentUser
     Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted

     Install-Module -Name 'Pester' -Scope CurrentUser -Force -SkipPublisherCheck
     Import-Module 'Pester' -Force

- task: PowerShell@1
  inputs:
    scriptType: inlineScript
    inlineScript: |
     $UnitTestParams = @{
        Script       = '.\PSCodeHealth\Tests'
        Strict       = $True
        CodeCoverage = '.\PSCodeHealth\task\Helpers.ps1'
     }
     Invoke-Pester @UnitTestParams

- task: qetza.replacetokens.replacetokens-task.replacetokens@2
  inputs:
    rootDirectory: PSCodeHealth
    targetFiles: |
     task\task.json
     vss-extension.json
    writeBOM: false
    actionOnMissing: fail

- task: ms-devlabs.vsts-developer-tools-build-tasks.package-extension-build-task.PackageVSTSExtension@1
  inputs:
    rootFolder: PSCodeHealth
    outputPath: '$(Build.ArtifactStagingDirectory)'
    extensionVisibility: private
    extensionPricing: free
  continueOnError: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'BuildArtifacts'
    publishLocation: Container
